//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhereIsMyMoney.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhereIsMyMoney.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        public static string AmountLabel {
            get {
                return ResourceManager.GetString("AmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a numeric value in amount..
        /// </summary>
        public static string AmountNumericValidation {
            get {
                return ResourceManager.GetString("AmountNumericValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter amount....
        /// </summary>
        public static string AmountPlaceHolder {
            get {
                return ResourceManager.GetString("AmountPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a value in amount..
        /// </summary>
        public static string AmountValidation {
            get {
                return ResourceManager.GetString("AmountValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready!.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where Was My Money?.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        public static string EmailValidation {
            get {
                return ResourceManager.GetString("You must enter an email.", resourceCulture);
            }
        }
         public static string EmailPlaceHolder {
            get {
                return ResourceManager.GetString("Enter your email...", resourceCulture);
            }
        }

        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme in this device", resourceCulture);
            }
        }


        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("You must enter a password.", resourceCulture);
            }
        }

         public static string SomethingWrong {
            get {
                return ResourceManager.GetString("Something was wrong, please try later.", resourceCulture);
            }
        }

         public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

         public static string EMail {
            get {
                return ResourceManager.GetString("E-Mail", resourceCulture);
            }
        }
 public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

 public static string PasswordPlaceHolder {
            get {
                return ResourceManager.GetString("Enter your password...", resourceCulture);
            }
        }

        
 public static string Forgot {
            get {
                return ResourceManager.GetString("Forgot your password?", resourceCulture);
            }
        }

        
 public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }

        
 public static string Search {
            get {
                return ResourceManager.GetString("Search...", resourceCulture);
            }
        }
        
        
 public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }

        
 public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
    }
}
